### ISSUE TITLE
Иногда генерируется нечитаемое сочетание цветов

### ISSUE THREAD

**Issue by vlanf** [Xel4ek/zappy#10]
![image](https://user-images.githubusercontent.com/25212107/141517376-79d2a56d-86a1-4949-895a-fa65d5fd4160.png)

Варианты:
- выбирать цвет текста в зависимости от цвета кружка (темное на светлом, светлое на темном)
- захардкодить палитры цветов
- сделать игроков одним цветом, цвет команды выделять обводкой кружка

**Comment by Xel4ek** [comment]
9af6ee9a06792dddd35dec08cc4a6d9d29880253
