### ISSUE TITLE
Фиксы чата

### ISSUE THREAD

**Issue by vlanf** [Xel4ek/zappy#11]
![image](https://user-images.githubusercontent.com/25212107/141686485-bb34eab9-6075-4efc-ad54-45aa5664b785.png)

1. Цвета это хорошо, но стало менее читаемо
2. Чат теперь сверху вниз, но нет автоскрола
3. Предлагаю сделать чат на всю левую часть экрана
4. Сделать чуть пошире, чтобы влезали дефолтные сообщения ("13110 took 2_0_1_0_0_0_0 ") в 1 строчку

**Comment by vlanf** [comment]
Для улучшения читаемости можно сделать так:

![image](https://user-images.githubusercontent.com/25212107/141687868-42161826-ec5d-4e1a-93ae-66809cf809af.png)

т.е. выделять цветом только само имя команды.

**Comment by Xel4ek** [comment]
69047f5521a77fca3b6146d5e9f3c96a42a3a10d
